services:
  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: order-management
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    volumes:
      - ./volumes/data/mysql:/var/lib/mysql
      - ./volumes/config/my.cnf:/etc/mysql/conf.d/my.cnf
